pretty print list.

diff --git a/.github/workflows/check-PR.yml b/.github/workflows/check-PR.yml
--- a/.github/workflows/check-PR.yml
+++ b/.github/workflows/check-PR.yml
@@ -23,10 +23,10 @@ jobs:
         if: steps.values_yaml_contains_version_suffix.outputs.result
         uses: mikefarah/yq@master
         with:
-          cmd: yq '[.secretsmanagement-operator.prereleaseSuffix, .secretsmanagement-operator.sidecarPrereleaseSuffix] | filter(.!=null and .!="")' charts/canvas-oda/values.yaml
+          cmd: yq '[.secretsmanagement-operator.prereleaseSuffix, .secretsmanagement-operator.sidecarPrereleaseSuffix] | filter(.!=null and .!="") | join(", ")' charts/canvas-oda/values.yaml
           
       - name: report error
         if: steps.values_yaml_contains_version_suffix.outputs.result
         run: |
-          echo "::error::values.yaml contains prereleaseSuffixes: '${{ steps.version_suffixes.outputs.result }}'" && exit 1
+          echo "::error::values.yaml contains prereleaseSuffixes: [${{ steps.version_suffixes.outputs.result }}]" && exit 1
 
